
[application]
#####################################
# Running config options        
#####################################
useTags		= 1				; Process tag rules.
dataSource	= smallroom_live		; Source name label. eg: work, router1, etc... 

#####################################
# JSON output options        
#####################################
writeFile	= 0				; Write files out to $fileDir instead of STDOUT
filePath	= /tmp/profile			; Path to write files to
filePrefix	= profile_			; prifix for the file names and or elastic index.
fileSuffix	= .json				; Filename suffix when writing files.
displayJson	= 0				; Enable JSON output

#####################################
# STDOUT options
#####################################
debug		= 0				; Enable debug output
logging		= 1				; Enable logging

#####################################
# ElasticSearch options 
#####################################
elastic		= 0				; use elasticsearch
esPrefix	= profile_			; elasticsearch index prefix
esNode		= 192.168.4.12:9200		; elasticsearch host, and port for injection

#####################################
# Packet Capture options 
#####################################
interface	= eth2				; Set the interface to listen to and profile.
l2Enable	= 1				; Enable Layer 2 collection details 0=off 1=on.
l7Enable	= 1				; Enable Layer 7 collection details 0=off 1=on.
ip6Enable	= 1				; Enable IPv6 collection details 0=off 1=on.
hwVendor	= 1				; Collect the vendor for all MAC addresses found.
ouiFile		= /home/flint/optimus/lib/wireshark_oui.txt	; Path for writing wireshark_oui.txt
ouiUrl		= https://gitlab.com/wireshark/wireshark/-/raw/master/manuf	; URL for obtaining wireshark OUIs
payload		= 1				; Collect payload sample on or off.
plBits		= 2048				; Number of bits from offset start_position to collect.
netFilter	= 0				; Enable destination subnet filter..
targetNet	= 192.168.1.0/24		; Subnets to to filter for separated by spaces.
sample		= 8000				; Packet samples to process. 0=unlimited packets
maxPerDest	= 0				; Max packtes per destination IP to record;
recType		= all				; Recording type: all, dist, flow, session.
geoip		= 1				; Enable Geo IP records.
geoipDat	= /usr/share/GeoIP/GeoLiteCity.dat	; Path to GeoLiteCity.dat
nameLookup	= 0;

