name: Test Optimus

on:
  push:
    branches:
      - "main"

jobs:
  test:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out Main
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install tzdata -y
          sudo apt-get install gzip wget cpanminus make gcc libpcap-dev net-tools libjson-perl libnet-pcap-perl libdata-dmp-perl libsys-hostname-long-perl libgetopt-long-descriptive-perl libuuid-tiny-perl libmaxmind-db-reader-perl libnet-ipaddress-perl libnetpacket-perl libuuid-tiny-perl libmaxmind-db-reader-perl libsearch-elasticsearch-perl php

      - name: Test Optimus
        run: |
          ifconfig -a
          ping 1.1.1.1 &
          cd /home/runner/work/optimus/optimus/bin
          perl -wc ./optimus.pl
          sudo ./optimus.pl -i eth0 -c 10 -j 
