name: Test Optimus

on:
  push:
    branches:
      - "main"

jobs:
  test:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out Optimus
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install tzdata -y
          sudo apt-get install gzip wget cpanminus make curl gcc libpcap-dev net-tools libjson-perl libnet-pcap-perl libdata-dmp-perl libsys-hostname-long-perl libgetopt-long-descriptive-perl libuuid-tiny-perl libmaxmind-db-reader-perl libnet-ipaddress-perl libnetpacket-perl libuuid-tiny-perl libmaxmind-db-reader-perl libsearch-elasticsearch-perl php apache2 libapache2-mod-php -y

      - name: Test Apache Configuration 
        run: |
          cd /home/runner/work/optimus/optimus
          sudo ln -s /home/runner/work/optimus/optimus /optimus
          sudo cp etc/apache2.conf /etc/apache2/apache2.conf
          sudo cp etc/php.ini /etc/php/8.1/apache2/php.ini
          sudo /etc/init.d/apache2 start
          sudo /etc/init.d/apache2 stop

      - name: Install and Run Elasticsearch
        run: |
          cd /opt
          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.5.2-linux-x86_64.tar.gz
          tar -zxvf elasticsearch-8.5.2-linux-x86_64.tar.gz
          adduser --disabled-password --gecos "" elastic
          chown -R elastic.elastic elasticsearch*
          cd /opt/elasticsearch-8.5.2
          echo "xpack.security.enabled: false" >> config/elasticsearch.yml
          su elastic -c "ES_PATH_CONF=/opt/elasticsearch-8.5.2/config bin/elasticsearch -d -p pid"

      - name: Test Elasticsearch Setup
        run: |
          cd /home/runner/work/optimus/optimus/bin
          ./elasticsearch_setup.sh localhost:9200

      - name: Test Optimus Execution
        run: |
          cd /home/runner/work/optimus/optimus/bin
          perl -wc ./optimus.pl
          sudo ./optimus.pl -p ../lib/examples/test.pcap -c 25 --bytes 1024 -g --l7 -j 
          sudo ./optimus.pl -p ../lib/examples/test.pcap -c 25 --bytes 1024 --l7 -d

      - name: Test Optimus API
        run: |
          cd /home/runner/work/optimus/optimus/web
          php -S localhost:8888 &
          sleep 5
          curl -F 'upload=@../lib/examples/test.pcap' http://localhost:8888

      - name: Test Docker Build
        run: |
          cd /home/runner/work/optimus/optimus
          docker build -t optimus .

      - name: Test Docker Image
        run: |
          docker run -d --rm -p 8000:8000 -p 4430:4430 -e OPTIMUS_ARGS='--dummy' --name=optimus_api optimus

